[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # Optional for future serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [context.production.environment]
    VITE_APP_ENV = "production"
    NODE_VERSION = "18"
    NPM_FLAGS = "--production"

# Development settings (optional)
[context.development]
  [context.development.environment]
    VITE_APP_ENV = "development"

[[headers]]
  for = "/pdf.worker.min.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/*.svg"
  [headers.values]
    "Content-Type" = "image/svg+xml"
